default_folder_icon = {
    "icon" : "",
    "color": "#f9d64d",
}

default_file_icon = {
    "icon" : "",
    "color": "white",
}

folder_icons = {
    '.github': {"icon":"", "color": "#f9d64d"},
    '.config': {"icon":"", "color": "#f9d64d"},
    'build'  : {"icon":"", "color": "#f9d64d"},
    'dist'   : {"icon":"", "color": "#f9d64d"},
    'image'  : {"icon":"", "color": "#f9d64d"},
    'images' : {"icon":"", "color": "#f9d64d"},
    'img'    : {"icon":"", "color": "#f9d64d"},
    'assets' : {"icon":"ﮛ", "color": "#f9d64d"},
}

named_icons = {
    'license'            : {"icon":"", "color": "#f9593f"},
    'licence'            : {"icon":"", "color": "#f9593f"},
    "readme"             : {"icon":"", "color": "#42a5f5"},
    "readme.md"          : {"icon":"", "color": "#42a5f5"},
    "paket.local"        : {"icon":"", "color": "#d8b558"},
    "nuget.config"       : {"icon":"", "color": "#d8b558"},
    "yarn.lock"          : {"icon":"", "color": "#80c836"},
    "package.json"       : {"icon":"", "color": "#80c836"},
    "package-lock.json"  : {"icon":"", "color": "#80c836"},
    "requirements.txt"   : {"icon":"", "color": "#4b8bbe"},
    "pipfile"            : {"icon":"", "color": "#4b8bbe"},
    "pipfile.lock"       : {"icon":"", "color": "#4b8bbe"},
    '.config'            : {"icon":"", "color": "#f9d64d"},
    ".gitignore"         : {"icon":"", "color": "#e54b36"},
    ".gitattributes"     : {"icon":"", "color": "#e54b36"},
    ".dockerfile"        : {"icon":"", "color": "#4b8bbe"},
    ".vscodeignore"      : {"icon":"", "color": "#3895f0"},
    "tasks.json"         : {"icon":"", "color": "#3895f0"},
    ".gemfile"           : {"icon":"", "color": "#701516"},
    "androidmanifest.xml": {"icon":"", "color": "#75b958"},
    ".htaccess"          : {"icon":"", "color": "#61a9cd"},
    "webpack.js"         : {"icon":"ﰩ", "color": "#8fcef0"},
    "karma.conf.js"      : {"icon":"", "color": "#59bc9f"},
    "gruntfile.js"       : {"icon":"", "color": "#eaa02d"},
    "gulpfile.js"        : {"icon":"", "color": "#db444b"},
    "brunch-config.js"   : {"icon":"﫱", "color": "#3f8348"},
    "eslintrc.js"        : {"icon":"", "color": "#4a2bb6"},
    "bower.json"         : {"icon":"", "color": "#eb563b"},
}

icons = {
    "styl"    : {"icon": "", "color": "#ff6347"},
    "sass"    : {"icon": "", "color": "#a53b70"},
    "scss"    : {"icon": "", "color": "#a53b70"},
    "bin"     : {"icon": "", "color": "#aaaaaa"},
    "dat"     : {"icon": "", "color": "#aaaaaa"},
    "htm"     : {"icon": "", "color": "#f06529"},
    "html"    : {"icon": "", "color": "#f06529"},
    "slim"    : {"icon": "", "color": "#f06529"},
    "pug"     : {"icon": "", "color": "#f06529"},
    "haml"    : {"icon": "", "color": "#dfd6a2"},
    "jade"    : {"icon": "", "color": "#4d9e6e"},
    "svg"     : {"icon": "ﰟ", "color": "#fcca3c"},
    "ejs"     : {"icon": "", "color": "#a91e50"},
    "css"     : {"icon": "", "color": "#375ee2"},
    "less"    : {"icon": "", "color": "#1d365d"},
    "ttf"     : {"icon": "", "color": "#165392"},
    "otf"     : {"icon": "", "color": "#165392"},
    "woff"    : {"icon": "", "color": "#165392"},
    "woff2"   : {"icon": "", "color": "#165392"},
    "md"      : {"icon": "", "color": "#50a4f2"},
    "markdown": {"icon": "", "color": "#50a4f2"},
    "rmd"     : {"icon": "", "color": "#50a4f2"},
    "json"    : {"icon": "", "color": "#e54b36"},
    "yaml"    : {"icon": "", "color": "#e54b36"},
    "xml"     : {"icon": "", "color": "#e54b36"},
    "js"      : {"icon": "", "color": "#e7d535"},
    "mjs"     : {"icon": "", "color": "#e7d535"},
    "jsx"     : {"icon": "", "color": "#e7d535"},
    "rb"      : {"icon": "", "color": "#701516"},
    "pub"     : {"icon": "", "color": "#f06529"},
    "php"     : {"icon": "", "color": "#4f5d95"},
    "py"      : {"icon": "", "color": "#4b8bbe"},
    "pyc"     : {"icon": "", "color": "#4b8bbe"},
    "pyo"     : {"icon": "", "color": "#4b8bbe"},
    "pyd"     : {"icon": "", "color": "#4b8bbe"},
    "coffee"  : {"icon": "", "color": "#244776"},
    "mustache": {"icon": "", "color": "#724b3b"},
    "hbs"     : {"icon": "", "color": "#e18b32"},
    "conf"    : {"icon": "", "color": "#50a4f2"},
    "cfg"     : {"icon": "", "color": "#50a4f2"},
    "ini"     : {"icon": "", "color": "#50a4f2"},
    "jpg"     : {"icon": "", "color": "cyan"},
    "jpeg"    : {"icon": "", "color": "cyan"},
    "bmp"     : {"icon": "", "color": "cyan"},
    "png"     : {"icon": "", "color": "cyan"},
    "gif"     : {"icon": "", "color": "cyan"},
    "ico"     : {"icon": "", "color": "cyan"},
    "twig"    : {"icon": "", "color": "#c1d026"},
    "cpp"     : {"icon": "", "color": "#165392"},
    "cxx"     : {"icon": "", "color": "#165392"},
    "cc"      : {"icon": "", "color": "#165392"},
    "cp"      : {"icon": "", "color": "#165392"},
    "c"       : {"icon": "", "color": "#19589a"},
    "cs"      : {"icon": "", "color": "#631d75"},
    "swift"   : {"icon": "ﯣ", "color": "#e04b3b"},
    "perl"    : {"icon": "🐫", "color": "#0c4064"},
    "h"       : {"icon": "", "color": "#165392"},
    "hpp"     : {"icon": "", "color": "#165392"},
    "hxx"     : {"icon": "", "color": "#165392"},
    "hs"      : {"icon": "", "color": "#5e5086"},
    "lhs"     : {"icon": "", "color": "#5e5086"},
    "lua"     : {"icon": "", "color": "#000080"},
    "java"    : {"icon": "", "color": "#b07219"},
    "sh"      : {"icon": "", "color": "magenta"},
    "fish"    : {"icon": "", "color": "green"},
    "bash"    : {"icon": "", "color": "white"},
    "zsh"     : {"icon": "", "color": "white"},
    "ksh"     : {"icon": "", "color": "white"},
    "csh"     : {"icon": "", "color": "white"},
    "awk"     : {"icon": "", "color": "white"},
    "ps1"     : {"icon": "", "color": "#4375cd"},
    "bat"     : {"icon": "", "color": "#aaaaaa"},
    "tex"     : {"icon": "", "color": "#167978"},
    "ml"      : {"icon": "λ", "color": "yellow"},
    "mli"     : {"icon": "λ", "color": "yellow"},
    "diff"    : {"icon": "", "color": "white"},
    "db"      : {"icon": "", "color": "#ea9d2d"},
    "sql"     : {"icon": "", "color": "#ea9d2d"},
    "dump"    : {"icon": "", "color": "#ea9d2d"},
    "clj"     : {"icon": "", "color": "green"},
    "cljc"    : {"icon": "", "color": "green"},
    "cljs"    : {"icon": "", "color": "green"},
    "edn"     : {"icon": "", "color": "green"},
    "scala"   : {"icon": "", "color": "red"},
    "go"      : {"icon": "", "color": "#27a3ca"},
    "dart"    : {"icon": "", "color": "#2074b8"},
    "xul"     : {"icon": "", "color": "light_red"},
    "sln"     : {"icon": "", "color": "#945db7"},
    "suo"     : {"icon": "", "color": "#945db7"},
    "pl"      : {"icon": "", "color": "blue"},
    "pm"      : {"icon": "", "color": "blue"},
    "t"       : {"icon": "", "color": "blue"},
    "rss"     : {"icon": "", "color": "#e25f2c"},
    "fsscript": {"icon": "", "color": "blue"},
    "fsx"     : {"icon": "", "color": "blue"},
    "fs"      : {"icon": "", "color": "#3eb0ce"},
    "fsi"     : {"icon": "", "color": "blue"},
    "rs"      : {"icon": "", "color": "#e64619"},
    "rlib"    : {"icon": "", "color": "#e64619"},
    "d"       : {"icon": "", "color": "#a73d37"},
    "erl"     : {"icon": "", "color": "magenta"},
    "ex"      : {"icon": "", "color": "magenta"},
    "exs"     : {"icon": "", "color": "magenta"},
    "eex"     : {"icon": "", "color": "magenta"},
    "hrl"     : {"icon": "", "color": "magenta"},
    "vim"     : {"icon": "", "color": "#149135"},
    "ai"      : {"icon": "", "color": "#f39523"},
    "psd"     : {"icon": "", "color": "#41c9fd"},
    "psb"     : {"icon": "", "color": "#41c9fd"},
    "ts"      : {"icon": "ﯤ", "color": "#3a73be"},
    "tsx"     : {"icon": "", "color": "#69d3f1"},
    "jl"      : {"icon": "", "color": "magenta"},
    "pp"      : {"icon": "", "color": "white"},
    "vue"     : {"icon": "﵂", "color": "#47b380"},
    "map"     : {"icon": "", "color": "#e6413b"},
    "pdf"     : {"icon": "", "color": "#e80117"},
    "zip"     : {"icon": "遲", "color": "#afb42b"},
}
